os: Visual Studio 2017

configuration:
  - Release

install:
  - "git submodule update --init --recursive"

before_build:
  - "\"C:/Program Files (x86)/Microsoft SDKs/Windows/v10.0A/bin/NETFX 4.6 Tools/sn.exe\" -k SwiftPbo/SwiftPbo/swiftpbokey.snk"
  - nuget restore

build:
  parallel: true
  project: DokanPbo.sln

artifacts:
  - path: DokanPbo\bin\Release\DokanPbo.exe
